FROM lopsided/archlinux:devel
RUN pacman --needed --noconfirm -Sy git cmake ca-certificates ca-certificates-utils
RUN pacman -S --noconfirm --overwrite ca-certificates ca-certificates-utils
RUN pacman --noconfirm -Scc
